### ISSUE TITLE
improvement abut tracker adding process

### ISSUE THREAD

**Issue by jfoucry** [Exodus-Privacy/etip#107]
Many times users like give us a large list of trackers;
@pnu-s already made a small shell script to check how mny times we found each of those tracker in our dataset.

My idea:
- improve the @pnu-s script and add it into the repository like a new tool;
The result of this script coult be a `csv` file with `name`,`code signature`,`number of found`
- add a entrypoint to, with another script, "inject" the result of the first script into etip.

Then we (the Exodus Team) could check in priority the most seens new tracker before adding them into the εxodus platform.

The two script (or only one with parameters is not a big deal.
The other point ask for more thinks to do. I could at least see those tasks. I can't imagine how much work they need: 
- add a field in to database;
- add a entrypoint;

Let's discuss about that if you want.

**Comment by pnu-s** [comment]
I think the approach is the right one.

1) The first script (basically already written) which takes a list of names and code signatures and queries exodus production machine files (as a first implementation) to give a csv file with the results

2) A second script which takes this csv and add the number into ETIP DB

I can actually implement this rather quickly if needed, my question is: is the number of matches enough? Do we need to add the date of the query as well? Or the total number of reports?

If so, that would be more complicated to manage.
