### ISSUE TITLE
add an export button

### ISSUE THREAD

**Issue by jawz101** [Exodus-Privacy/etip#11]
It would be nice to be able to pull all of the entries out in txt, csv, xml, or json to be able to review it or to use and test in other implementations

**Comment by simpnu** [comment]
Hi @jawz101 
Do you have more details about what information in particular you would need in this export ? (and maybe a preferred format?)

Thanks !

**Comment by jawz101** [comment]
title, code sig, network sig, and homepage at minimum.  If someone else on the project thinks making more of the fields exportable perhaps more could be added.  xml might be the easiest to work with if needed to consume into another program.

I was also wondering if we could have a separate field for url to the support documentation for sdk integration instructions since we all kinda throw them in either the short or long description field.  Perhaps sdk documentation/support url's warrant their own field?

**Comment by simpnu** [comment]
@jawz101 Ok thanks! I think we can see to export all of them, just need to see how manageable that is. 
For your second point I opened a separate issue ;)

**Comment by simpnu** [comment]
@ammelanie is currently implementing this feature :).
