### ISSUE TITLE
Add Pangle SDK

### ISSUE THREAD

**Issue by MuntashirAkon** [Exodus-Privacy/etip#111]
From my list:

      "name": "Pangle SDK",
      "description": "",
      "creation_date": "",
      "code_signature": "com.bytedance.sdk.openadsdk",
      "network_signature": "",
      "website": "https://www.pangleglobal.com"

**Comment by pnu-s** [comment]
It's in ETIP, will go to exodus soon: https://etip.exodus-privacy.eu.org/trackers/7af9c3e5-bed5-46ad-8549-ef5fa0e97443/

Cheers!
