### ISSUE TITLE
sentry.io

### ISSUE THREAD

**Issue by kasnder** [Exodus-Privacy/etip#117]
Code signature: `io.sentry|com.joshdholtz.sentry`

Manifest: `io.sentry.dsn`

URL1: `https://github.com/getsentry/sentry-java`
URL2: `https://github.com/joshdholtz/Sentry-Android`

**Comment by pnu-s** [comment]
We already had a profile on ETIP, I updated it accordingly: https://etip.exodus-privacy.eu.org/trackers/8e73558e-9a1d-4e05-b91e-3fbf4b2fc0f1/
