### ISSUE TITLE
Regex in signatures

### ISSUE THREAD

**Issue by simpnu** [Exodus-Privacy/etip#12]
I've made a bunch of changes this weekend to a lot of entries on the etip site, including adding several additional subdomains for sites.  In this example screenshot, does Exodus look for network signatures using regex or full domains?  Could all of the <subdomain>.adcolony.com's simply be replaced with `.*\.adcolony\.com.*` or `.*adcolony.*` ?  If so, I would think several rules could be shortened.

_Originally posted by @jawz101 in https://github.com/Exodus-Privacy/exodus/issues/126#issuecomment-451318266_

**Comment by jawz101** [comment]
[exodus_spreadsheet.xlsx](https://github.com/Exodus-Privacy/etip/files/2908069/exodus_spreadsheet.xlsx)

**Comment by simpnu** [comment]
Closing this issue, the same discussion is happening on #13
