### ISSUE TITLE
Export full data dump

### ISSUE THREAD

**Issue by ivbeg** [Exodus-Privacy/etip#126]
Right now it's possible to download the only a list of trackers from https://etip.exodus-privacy.eu.org/trackers/export and this export file doesn't contain even the ID of the tracker in ETIP, which is UUID like identifier.

For many usages, it's important to have a dump with full data on each tracker. 
Please provide a full dump of collected data.

**Comment by pnu-s** [comment]
Sorry for closing/re-opening the issue, just miss-clicked!

**Comment by pnu-s** [comment]
@ivbeg I'm taking a look at your issue and I'm wondering what would be the best approach.

We could simply add some fields to the existing export feature. Which field is really missing for you, except the `id`?

**Comment by ivbeg** [comment]
@pnu-s If you export JSON, it's a good practice to publish all public fields from tracker's card.

**Comment by ivbeg** [comment]
The dump is not complete, only a few fields exported. Please, reopen
