### ISSUE TITLE
Any data license like Creative Commons?

### ISSUE THREAD

**Issue by ivbeg** [Exodus-Privacy/etip#127]
ETIP mentioned _as "ETIP is free and open source, feel free to check its GitHub page._" at https://etip.exodus-privacy.eu.org/
and  AGPL-3.0 License mentioned for https://github.com/Exodus-Privacy/etip

But there is no license or terms for data collected in ETIP. If I reuse ETIP data in any publication or project when what should I do?

I think it's important to set common rules on contribution and usage of this data like Creative Commons license CC-BY 4.0 https://creativecommons.org/licenses/by/4.0/

**Comment by ivbeg** [comment]
Up!

 Is there any chance to dataset under Creative Commons?

**Comment by pnu-s** [comment]
Hello @ivbeg 

You are right, sorry for the delayed answer

We will use the license ODbL, see https://github.com/Exodus-Privacy/etip/issues/159
