### ISSUE TITLE
Automatically generate release

### ISSUE THREAD

**Issue by pnu-s** [Exodus-Privacy/etip#128]
It would be nice if a release could be automatically created for each new tag, with the list of commits in its description

See existing releases of this repo for examples.

**Comment by Jean-BaptisteC** [comment]
Do you want use same workflow or create another to generate release ?

**Comment by pnu-s** [comment]
I don't really mind, whatever is the more readable :)

**Comment by Jean-BaptisteC** [comment]
Done with https://github.com/Exodus-Privacy/etip/commit/8b1601c3e8798d63fa16c8f3f88200a917d0ca8c
