### ISSUE TITLE
page crash when signature contains *

### ISSUE THREAD

**Issue by jawz101** [Exodus-Privacy/etip#13]
https://etip.exodus-privacy.eu.org/?page=11

error at /

nothing to repeat at position 0

Request Method: 	GET
Request URL: 	http://etip.exodus-privacy.eu.org/?page=11
Django Version: 	2.0.3
Exception Type: 	error
Exception Value: 	

nothing to repeat at position 0

Exception Location: 	/home/etip/etip/venv/lib/python3.5/sre_parse.py in _parse, line 638
Python Executable: 	/home/etip/etip/venv/bin/python3.5
Python Version: 	3.5.3
Python Path: 	

['/home/etip/etip/etip',
 '/home/etip/etip/venv/bin',
 '/home/etip/etip/venv/lib/python35.zip',
 '/home/etip/etip/venv/lib/python3.5',
 '/home/etip/etip/venv/lib/python3.5/plat-x86_64-linux-gnu',
 '/home/etip/etip/venv/lib/python3.5/lib-dynload',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/home/etip/etip/venv/lib/python3.5/site-packages']

Server time: 	Sat, 23 Feb 2019 18:35:34 +0000
Error during template rendering

In template /home/etip/etip/etip/trackers/templates/base.html, error at line 0
nothing to repeat at position 0
1 	<!doctype html>
2 	<html>
3 	<head>
4 	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
5 	    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
6 	    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
7 	    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js" integrity="sha384-feJI7QwhOS+hwpX2zkaeJQjeiwlhOP+SdQDqhgvvo1DsjtiSQByFdThsxO669S2D" crossorigin="anonymous"></script>
8 	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
9 	    <style>
10 	        html {
Traceback Switch to copy-and-paste view

    /home/etip/etip/venv/lib/python3.5/site-packages/django/core/handlers/exception.py in inner

                    response = get_response(request)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/core/handlers/base.py in _get_response

                        response = self.process_exception_by_middleware(e, request)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/core/handlers/base.py in _get_response

                        response = wrapped_callback(request, *callback_args, **callback_kwargs)

         ...
    ▶ Local vars
    /home/etip/etip/etip/trackers/views.py in index

                'count': count

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/shortcuts.py in render

            content = loader.render_to_string(template_name, context, request, using=using)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/loader.py in render_to_string

            return template.render(context, request)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/backends/django.py in render

                    return self.template.render(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in render

                            return self._render(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in _render

                return self.nodelist.render(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in render

                        bit = node.render_annotated(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in render_annotated

                    return self.render(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/loader_tags.py in render

                    return compiled_parent._render(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in _render

                return self.nodelist.render(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in render

                        bit = node.render_annotated(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in render_annotated

                    return self.render(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/loader_tags.py in render

                        result = block.nodelist.render(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in render

                        bit = node.render_annotated(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in render_annotated

                    return self.render(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/defaulttags.py in render

                        return nodelist.render(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in render

                        bit = node.render_annotated(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in render_annotated

                    return self.render(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/defaulttags.py in render

                            nodelist.append(node.render_annotated(context))

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in render_annotated

                    return self.render(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/defaulttags.py in render

                            match = condition.eval(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/defaulttags.py in eval

                return self.value.resolve(context, ignore_failures=True)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in resolve

                        obj = self.var.resolve(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in resolve

                    value = self._resolve_lookup(context)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/site-packages/django/template/base.py in _resolve_lookup

                                    current = current()

         ...
    ▶ Local vars
    /home/etip/etip/etip/trackers/models.py in network_signature_collision

                    if re.search(self.network_signature, t.network_signature) \

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/re.py in search

            return _compile(pattern, flags).search(string)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/re.py in _compile

            p = sre_compile.compile(pattern, flags)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/sre_compile.py in compile

                p = sre_parse.parse(p, flags)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/sre_parse.py in parse

            p = _parse_sub(source, pattern, 0)

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/sre_parse.py in _parse_sub

                itemsappend(_parse(source, state))

         ...
    ▶ Local vars
    /home/etip/etip/venv/lib/python3.5/sre_parse.py in _parse

                                           source.tell() - here + len(this))

         ...
    ▶ Local vars

Request information
USER

AnonymousUser
GET
Variable 	Value
page 	

'11'

POST

No POST data
FILES

No FILES data
COOKIES

No cookie data
META
Variable 	Value
HTTP_ACCEPT 	

'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'

HTTP_ACCEPT_ENCODING 	

'gzip, deflate, br'

HTTP_ACCEPT_LANGUAGE 	

'en-US,en;q=0.5'

HTTP_CONNECTION 	

'close'

HTTP_DNT 	

'1'

HTTP_HOST 	

'etip.exodus-privacy.eu.org'

HTTP_UPGRADE_INSECURE_REQUESTS 	

'1'

HTTP_USER_AGENT 	

'Mozilla/5.0 (Android 6.0; Mobile; rv:60.0) Gecko/20100101 Firefox/60.0'

HTTP_X_FORWARDED_FOR 	

'107.242.113.9'

HTTP_X_FORWARDED_PROTO 	

'https'

HTTP_X_REAL_IP 	

'107.242.113.9'

PATH_INFO 	

'/'

QUERY_STRING 	

'page=11'

RAW_URI 	

'/?page=11'

REMOTE_ADDR 	

'217.70.189.62'

REMOTE_PORT 	

'38466'

REQUEST_METHOD 	

'GET'

SCRIPT_NAME 	

''

SERVER_NAME 	

'0.0.0.0'

SERVER_PORT 	

'8899'

SERVER_PROTOCOL 	

'HTTP/1.0'

SERVER_SOFTWARE 	

'gunicorn/19.7.1'

gunicorn.socket 	

<socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('217.70.190.114', 8899), raddr=('217.70.189.62', 38466)>

wsgi.errors 	

<gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7f051183ff28>

wsgi.file_wrapper 	

''

wsgi.input 	

<gunicorn.http.body.Body object at 0x7f051183f048>

wsgi.multiprocess 	

False

wsgi.multithread 	

False

wsgi.run_once 	

False

wsgi.url_scheme 	

'http'

wsgi.version 	

(1, 0)

Settings
Using settings module etip.settings
Setting 	Value
ABSOLUTE_URL_OVERRIDES 	

{}

ADMINS 	

[]

ALLOWED_HOSTS 	

['etip.exodus-privacy.eu.org']

APPEND_SLASH 	

True

AUTHENTICATION_BACKENDS 	

['django.contrib.auth.backends.ModelBackend']

AUTH_PASSWORD_VALIDATORS 	

'********************'

AUTH_USER_MODEL 	

'auth.User'

BASE_DIR 	

'/home/etip/etip/etip'

CACHES 	

{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}

CACHE_MIDDLEWARE_ALIAS 	

'default'

CACHE_MIDDLEWARE_KEY_PREFIX 	

'********************'

CACHE_MIDDLEWARE_SECONDS 	

600

CSRF_COOKIE_AGE 	

31449600

CSRF_COOKIE_DOMAIN 	

None

CSRF_COOKIE_HTTPONLY 	

False

CSRF_COOKIE_NAME 	

'csrftoken'

CSRF_COOKIE_PATH 	

'/'

CSRF_COOKIE_SECURE 	

False

CSRF_FAILURE_VIEW 	

'django.views.csrf.csrf_failure'

CSRF_HEADER_NAME 	

'HTTP_X_CSRFTOKEN'

CSRF_TRUSTED_ORIGINS 	

[]

CSRF_USE_SESSIONS 	

False

DATABASES 	

{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.sqlite3',
             'HOST': '',
             'NAME': '/home/etip/etip/etip/db.sqlite3',
             'OPTIONS': {},
             'PASSWORD': '********************',
             'PORT': '',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': None,
             'USER': ''}}

DATABASE_ROUTERS 	

[]

DATA_UPLOAD_MAX_MEMORY_SIZE 	

2621440

DATA_UPLOAD_MAX_NUMBER_FIELDS 	

1000

DATETIME_FORMAT 	

'N j, Y, P'

DATETIME_INPUT_FORMATS 	

['%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y']

DATE_FORMAT 	

'N j, Y'

DATE_INPUT_FORMATS 	

['%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y']

DEBUG 	

True

DEBUG_PROPAGATE_EXCEPTIONS 	

False

DECIMAL_SEPARATOR 	

'.'

DEFAULT_CHARSET 	

'utf-8'

DEFAULT_CONTENT_TYPE 	

'text/html'

DEFAULT_EXCEPTION_REPORTER_FILTER 	

'django.views.debug.SafeExceptionReporterFilter'

DEFAULT_FILE_STORAGE 	

'django.core.files.storage.FileSystemStorage'

DEFAULT_FROM_EMAIL 	

'webmaster@localhost'

DEFAULT_INDEX_TABLESPACE 	

''

DEFAULT_TABLESPACE 	

''

DISALLOWED_USER_AGENTS 	

[]

EMAIL_BACKEND 	

'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST 	

'localhost'

EMAIL_HOST_PASSWORD 	

'********************'

EMAIL_HOST_USER 	

''

EMAIL_PORT 	

25

EMAIL_SSL_CERTFILE 	

None

EMAIL_SSL_KEYFILE 	

'********************'

EMAIL_SUBJECT_PREFIX 	

'[Django] '

EMAIL_TIMEOUT 	

None

EMAIL_USE_LOCALTIME 	

False

EMAIL_USE_SSL 	

False

EMAIL_USE_TLS 	

False

FILE_CHARSET 	

'utf-8'

FILE_UPLOAD_DIRECTORY_PERMISSIONS 	

None

FILE_UPLOAD_HANDLERS 	

['django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler']

FILE_UPLOAD_MAX_MEMORY_SIZE 	

2621440

FILE_UPLOAD_PERMISSIONS 	

None

FILE_UPLOAD_TEMP_DIR 	

None

FIRST_DAY_OF_WEEK 	

0

FIXTURE_DIRS 	

[]

FORCE_SCRIPT_NAME 	

None

FORMAT_MODULE_PATH 	

None

FORM_RENDERER 	

'django.forms.renderers.DjangoTemplates'

IGNORABLE_404_URLS 	

[]

INSTALLED_APPS 	

['trackers',
 'reversion',
 'bootstrap3',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']

INTERNAL_IPS 	

[]

LANGUAGES 	

[('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('dsb', 'Lower Sorbian'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-co', 'Colombian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gd', 'Scottish Gaelic'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hsb', 'Upper Sorbian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kab', 'Kabyle'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmål'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese')]

LANGUAGES_BIDI 	

['he', 'ar', 'fa', 'ur']

LANGUAGE_CODE 	

'en-us'

LANGUAGE_COOKIE_AGE 	

None

LANGUAGE_COOKIE_DOMAIN 	

None

LANGUAGE_COOKIE_NAME 	

'django_language'

LANGUAGE_COOKIE_PATH 	

'/'

LOCALE_PATHS 	

[]

LOGGING 	

{}

LOGGING_CONFIG 	

'logging.config.dictConfig'

LOGIN_REDIRECT_URL 	

'/accounts/profile/'

LOGIN_URL 	

'/accounts/login/'

LOGOUT_REDIRECT_URL 	

None

MANAGERS 	

[]

MEDIA_ROOT 	

''

MEDIA_URL 	

''

MESSAGE_STORAGE 	

'django.contrib.messages.storage.fallback.FallbackStorage'

MIDDLEWARE 	

['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

MIGRATION_MODULES 	

{}

MONTH_DAY_FORMAT 	

'F j'

NUMBER_GROUPING 	

0

PASSWORD_HASHERS 	

'********************'

PASSWORD_RESET_TIMEOUT_DAYS 	

'********************'

PREPEND_WWW 	

False

ROOT_URLCONF 	

'etip.urls'

SECRET_KEY 	

'********************'

SECURE_BROWSER_XSS_FILTER 	

False

SECURE_CONTENT_TYPE_NOSNIFF 	

False

SECURE_HSTS_INCLUDE_SUBDOMAINS 	

False

SECURE_HSTS_PRELOAD 	

False

SECURE_HSTS_SECONDS 	

0

SECURE_PROXY_SSL_HEADER 	

None

SECURE_REDIRECT_EXEMPT 	

[]

SECURE_SSL_HOST 	

None

SECURE_SSL_REDIRECT 	

False

SERVER_EMAIL 	

'root@localhost'

SESSION_CACHE_ALIAS 	

'default'

SESSION_COOKIE_AGE 	

1209600

SESSION_COOKIE_DOMAIN 	

None

SESSION_COOKIE_HTTPONLY 	

True

SESSION_COOKIE_NAME 	

'sessionid'

SESSION_COOKIE_PATH 	

'/'

SESSION_COOKIE_SECURE 	

False

SESSION_ENGINE 	

'django.contrib.sessions.backends.db'

SESSION_EXPIRE_AT_BROWSER_CLOSE 	

False

SESSION_FILE_PATH 	

None

SESSION_SAVE_EVERY_REQUEST 	

False

SESSION_SERIALIZER 	

'django.contrib.sessions.serializers.JSONSerializer'

SETTINGS_MODULE 	

'etip.settings'

SHORT_DATETIME_FORMAT 	

'm/d/Y P'

SHORT_DATE_FORMAT 	

'm/d/Y'

SIGNING_BACKEND 	

'django.core.signing.TimestampSigner'

SILENCED_SYSTEM_CHECKS 	

[]

STATICFILES_DIRS 	

[]

STATICFILES_FINDERS 	

['django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder']

STATICFILES_STORAGE 	

'django.contrib.staticfiles.storage.StaticFilesStorage'

STATIC_ROOT 	

None

STATIC_URL 	

'/static/'

TEMPLATES 	

[{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': [],
  'OPTIONS': {'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages']}}]

TEST_NON_SERIALIZED_APPS 	

[]

TEST_RUNNER 	

'django.test.runner.DiscoverRunner'

THOUSAND_SEPARATOR 	

','

TIME_FORMAT 	

'P'

TIME_INPUT_FORMATS 	

['%H:%M:%S', '%H:%M:%S.%f', '%H:%M']

TIME_ZONE 	

'UTC'

USE_ETAGS 	

False

USE_I18N 	

True

USE_L10N 	

True

USE_THOUSAND_SEPARATOR 	

False

USE_TZ 	

True

USE_X_FORWARDED_HOST 	

False

USE_X_FORWARDED_PORT 	

False

WSGI_APPLICATION 	

'etip.wsgi.application'

X_FRAME_OPTIONS 	

'SAMEORIGIN'

YEAR_MONTH_FORMAT 	

'F Y'

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.

**Comment by simpnu** [comment]
Thanks @jawz101 for reporting it!

The issue came from Python wrongly interpreting the following signature "*content.swrve.com|*api.swrve.com" in the function network_signature_collision of trackers/models.py

For now I modified the signature so that the page doesn't crash anymore, but we need to figure out a fix.

**Comment by jawz101** [comment]
that doesn't even look like a valid regex expression if it's meant to wildcard anything preceding

**Comment by ammelanie** [comment]
I've faced some other issues in local with invalid regex, leading to errors: 

```
\criteo.com
\cmcm.com
\optimizely.com
*.dov-e.com
```

What do you think about adding a check to verify that the regex is valid before saving the tracker? 
Maybe, we can do it with `re` inside a try / except block, for example: 

```
re.compile('\criteo.com')
``` 

is raising an exception:

```
raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \c at position 0
``` 

I don't know if it's easy to do such validation with the django admin, but I think, it will avoid to have these kind of errors.

**Comment by jawz101** [comment]
I say we just go cowboy and fix all of the regex's.  I use it all the time for work but I don't know what the project wants it to look like.

Ex:
```
com\.criteo\.
com\.criteo
^com\.criteo\.
com\.criteo\.*$
\.criteo\.
```

etc.

Maybe we should take all of our regex attempts out of ETIP and just have them be the string of characters we recognize but only using dots, hyphens, letters, and numbers.  Then the maintainers put their regex'd translation in a box that is read-only to us.

**Comment by simpnu** [comment]
FYI we released to ETIP the regex validation made by @ammelanie
