### ISSUE TITLE
do not detect bugsnag?

### ISSUE THREAD

**Issue by openffchrome** [Exodus-Privacy/etip#15]
exodus do not detect bugsnag present in apps such as standartnotes https://reports.exodus-privacy.eu.org/en/reports/search/com.standardnotes/

thanks.

**Comment by simpnu** [comment]
I checked today with the code signature "com.bugsnag." and it is detected in 482 reports currently (out of 70000+).

We could easily add it to ETIP then to Exodus.

**Comment by simpnu** [comment]
Added to ETIP today

**Comment by openffchrome** [comment]
thanks, it's not possible to add newly added trackers retroactively to reports?

**Comment by simpnu** [comment]
@openffchrome We need to update the whole set of 80000+ reports. We have a way of doing so, we just don't do it after each update of the trackers DB (it takes a while to update the set, as you can imagine :)).

I'll try to do it during this week though, I'll keep you posted.

**Comment by simpnu** [comment]
@openffchrome Here you go :) https://reports.exodus-privacy.eu.org/en/reports/search/com.standardnotes/
