### ISSUE TITLE
Add Copilot Analytics

### ISSUE THREAD

**Issue by Eonfge** [Exodus-Privacy/etip#162]
Copilot
https://www.copilot.cx/

>Copilot.cx, is the only consumer electronics focused solution to turn your transactional customers into prime users that continuously benefit your brand.

## Details
- Gradle package: `com.copilot:copilot-api-access:X.Y.Z`
- AndroidManifest: `com.copilot.XXX`
- Imports: `com.copilot.analytics._`
- Endpoints: `https://api.XXX.bycopilot.com`

**Comment by Jean-BaptisteC** [comment]
Added https://etip.exodus-privacy.eu.org/trackers/fa2d823b-5b3e-4d5a-8ec6-82aad1199263/ :)

**Comment by pnu-s** [comment]
Closing the issue as the tracker has been added to ETIP (thanks @Jean-BaptisteC)
