### ISSUE TITLE
Add Vungle to Tracker Definitions

### ISSUE THREAD

**Issue by peterstory** [Exodus-Privacy/etip#2]
The Vungle advertising library seems like a prominent omission from the list of trackers supported by Exodus, since [it is quite popular](https://www.appbrain.com/stats/libraries/details/vungle/vungle). 

Thankfully, it should be easy to add, because Vungle makes [example code publicly available](https://github.com/Vungle/Android-SDK/blob/d1b90fcf5b0c7a9c98af3d8fc8bbc2372b862064/app/src/main/java/com/publisher/sample/MainActivity.java#L12-L19). 

(I'm not sure if this is the appropriate repo for this issue, sorry if it's in the wrong place!)

**Comment by simpnu** [comment]
Hi @peterstory 
Vungle is already in the ETIP database thanks to @jawz101. We now need to find time to add it to Exodus.

**Comment by jawz101** [comment]
@simpnu is there a way I can ask you some quick questions somewhere?  I didn't know if just asking on here would muddy up the issue tracker.

**Comment by simpnu** [comment]
@jawz101 Sure! If it's about the management of trackers I think it's not a problem if you create an issue here, but if you prefer feel free to come to our IRC channel or send us a mail. :) All the details are here: https://exodus-privacy.eu.org/en/page/who/

**Comment by MuntashirAkon** [comment]
@pnu-s Vungle has a new signature: `com.vungle.warren.`
