### ISSUE TITLE
Categories on Trackers

### ISSUE THREAD

**Issue by IzzySoft** [Exodus-Privacy/etip#31]
I miss a form of categorizing for the trackers – i.e. whether they are analytics, ads, social (Facebook and the likes), payment, whatever.

For context: I currently use the Appbrain API to identify "snooping modules". They have 2 fields for that:

* types: dev, ad, social (usually only one of them set)
* tags: e.g. analytics, mediation, billing (often more than one used)

both are arrays. Full details can be found at: https://www.appbrain.com/info/help/api/specification.html

I was able to match 40 of the "exodus libraries" against Appbrain's list (which I currently use), but failed for 95. For those 95 I miss some categorizing to merge them. Could that be added?

Sure I could walk those 95 and evaluate them manually – but it's not really practicable to do that on a permanent basis (as it would have to be repeated at least every time changes are made or new libraries added). It would be great to at least have one category field distinguishing ads, analytics, payment, social, misc.

That possible? I could help you with the initial set, matching the current ones, if that would get things running. In that case please let me know if you want to adopt both fields or just one. It would also be good to know which field of the set is a "unique identifier". Is the same ID field always matching the very same library?

**Comment by IzzySoft** [comment]
Thanks @simpnu! My offer with the initial set still stands once you've decided. Just let me know and I see to make a dump (SQL script generated by `mysqldump`) available for you.

**Comment by simpnu** [comment]
Thanks a lot @IzzySoft that would be great. 
For now our initial proposal (to be discussed and improved) is to go with the following list:
- Crash reporting
- Analytics
- Profiling
- Identification
- Advertisement
- Location

(taken from the article - in French - by @U039b: https://esther.codes/exodus-et-les-pisteurs/)

@IzzySoft @jawz101 Would you have any feedback on this list? Thanks!

**Comment by IzzySoft** [comment]
Sounds like a plan! What would things like Facebook Login/Share etc. (as opposed to e.g. FB Analytics) fall into then? Profiling? Identification? Location? Is another category needed for that ("Social" doesn't necessarily imply tracking)? Are combinations possible (so all 3 could apply)? Would it be left out when nothing fits?

As for the dump: tell me when, and where to send it to. It'd better be as up-to-date as possible when needed :wink:

**Comment by simpnu** [comment]
If nothing fits, then I think we need to add a new category / modify the proposed ones. Our idea was indeed that we can add multiple ones to a single tracker, **if they all apply**.

**Comment by simpnu** [comment]
Hi @IzzySoft 
The codebase changes to add tracker categories in ETIP were just merged (and we will release them to the live instance shortly). I used the following categories, as discussed:
- Crash reporting
- Analytics
- Profiling
- Identification
- Advertisement
- Location

What do you think is the easiest way we can fill these categories?

**Comment by IzzySoft** [comment]
As I suggested, I could provide you a dump from my database – were Exodus library definitions are merged with Appbrain's which already have comparable categories, so you should be able to map them (that's how I solved this issue for me already – as long as the Exodus library can be mapped to its Appbrain pendant, which is mostly the case):

[libs.zip](https://github.com/Exodus-Privacy/etip/files/3209073/libs.zip)

Column names should be easy to interpret. If you need help (or a fresh version of the table), just let me know :smiley:

**Comment by simpnu** [comment]
Thanks @IzzySoft! :)
I converted it to JSON and made a quick python script to check the entries. Right now there are 110 entries with both "_exodus_id_" and "_tags_". That doesn't cover the entirety of our set but that will definitely be useful! I'll try to make somehow a script to add the entries to ETIp without doing it manually ;).

We need to match the following tags to the ones listed above:
- billing
- android_utility
- video_ads
- native_ads
- game
- mediation
- maps
- online_service
- social gaming
- install_attribution
- authentication
- audio

**Comment by IzzySoft** [comment]
Glad to read it's helpful, @simpnu! I might have missed some matches when merging the Exodus list – but I'm pretty sure it's not fully covered by Appbrain's (and vice versa). Should you spot entries not having an exodus_id which should have one, corrections are welcome! And the other way around: if there were new trackers added after 11/2018 and missing for that reason, I'd update my merge script and send you a fresh dump. E.g. for some reason, the following I've not added (they aren't at Appbrain):

```sql
,('crowdtangle',46,NULL,'/','CrowdTangle','https://www.crowdtangle.com/',NULL,'content discovery and social monitoring platform','ats',',analytics,',',dev,'
,('jwpltx',8,NULL,'/','JWPLTx','http://JWPLTx.com',NULL,'pop-up ads','ats',NULL,',ad,')
,('tencent_weiyun',117,NULL,'com/tencent/weiyun','Tencent Weiyun','https://www.weiyun.com',NULL,'cloud storage','ats',',analytics,',',dev,') -- Exodus: Anal
,('ultimedia',19,NULL,'/','Ultimedia','http://ultimedia.com',NULL,'','ats',',analytics,',',dev,') -- no details
,('widespace',14,NULL,'/','Widespace','http://widespace.com',NULL,'','ats',',analytics,',',dev,')
,('xiti',10,NULL,'','Xiti','http://Xiti.com',NULL,'','ats',',analytics,',',dev,')
```

(second field should be the exodus_id; found this block commented out in my merge script so it's missing from the dump). Running my "check-what-might-be-missing" script again, the list gets a bit longer:

``` sql
('jw_player',8,NULL,'com/longtailvideo/jwplayer/','JW Player','https://jwplayer.com',NULL,'','ats','analytics',',dev,')
('xiti',10,NULL,'NC','Xiti','http://Xiti.com',NULL,'','ats','analytics',',dev,')
('widespace',14,NULL,'com/widespace/','Widespace','http://widespace.com',NULL,'','ats','analytics',',dev,')
('crowdtangle',46,NULL,'/','CrowdTangle','https://www.crowdtangle.com/',NULL,'','ats','analytics',',dev,')
('tencent_weiyun',117,NULL,'com/tencent/weiyun','Tencent Weiyun','https://www.weiyun.com',NULL,'','ats','analytics',',dev,')
('placed',160,NULL,'com/placed/client','Placed','http://placed.com/',NULL,'','ats','analytics',',dev,')
('adot',161,NULL,'com/adotmob','Adot','https://we-are-adot.com/',NULL,'','ats','analytics',',dev,')
('appmonet',163,NULL,'com/monet/','AppMonet','http://appmonet.com',NULL,'','ats','analytics',',dev,')
('adincube',165,NULL,'com/adincube/sdk/','Adincube','https://www.adincube.com/',NULL,'','ats','analytics',',dev,')
('persona.ly',166,NULL,'ly/persona/sdk','Persona.ly','http://persona.ly/',NULL,'','ats','analytics',',dev,')
('cheetah_ads',168,NULL,'com/cmcm/','Cheetah Ads','https://www.cmcm.com/',NULL,'','ats','analytics',',dev,')
('criteo',170,NULL,'com/criteo/','Criteo','https://www.criteo.com/',NULL,'','ats','analytics',',dev,')
('mytracker',175,NULL,'com/my/tracker/','myTracker','https://tracker.my.com/',NULL,'','ats','analytics',',dev,')
('cloudmobi',176,NULL,'com/cloudtech/','Cloudmobi','http://www.cloudmobi.net/',NULL,'','ats','analytics',',dev,')
('brightcove',178,NULL,'com/brightcove','Brightcove','https://www.brightcove.com',NULL,'','ats','analytics',',dev,')
('dov-e',179,NULL,'com/dv/','DOV-E','https://www.dov-e.com/',NULL,'','ats','analytics',',dev,')
('inmarket',180,NULL,'com/inmarket','Inmarket','https://inmarket.com/',NULL,'','ats','analytics',',dev,')
('pilgrim',181,NULL,'com/foursquare/pilgrim|com/foursquare/pilgrimsdk/android','Pilgrim','https://enterprise.foursquare.com/products/pilgrim',NULL,'','ats','analytics',',dev,')
('otherlevels',182,NULL,'com/otherlevels/','OtherLevels','https://www.otherlevels.com/',NULL,'','ats','analytics',',dev,')
('shallwead',186,NULL,'com/jm/co/shallwead/sdk/|com/co/shallwead/sdk/','ShallWeAD','http://www.shallwead.com',NULL,'','ats','analytics',',dev,')
('deltadna',187,NULL,'com/deltadna','deltaDNA','https://deltadna.com/',NULL,'','ats','analytics',',dev,')
('display',188,NULL,'io/display/','Display','https://www.display.io/en/',NULL,'','ats','analytics',',dev,')
('bugly',190,NULL,'com/tencent/bugly/','Bugly','https://bugly.qq.com/v2/',NULL,'','ats','analytics',',dev,')
('swrve',192,NULL,'com/swrve/sdk','Swrve','https://www.swrve.com/',NULL,'','ats','analytics',',dev,')
('appdynamics',194,NULL,'com/appdynamics/','Appdynamics','https://www.appdynamics.com/',NULL,'','ats','analytics',',dev,')
('infonline',197,NULL,'de/infonline/','INFOnline','https://www.infonline.de',NULL,'','ats','analytics',',dev,')
('mintegral',200,NULL,'com/mintegral/','Mintegral','https://www.mintegral.com/en/',NULL,'','ats','analytics',',dev,')
('gimbal',201,NULL,'com/gimbal/android','Gimbal','https://gimbal.com/',NULL,'','ats','analytics',',dev,')
('conviva',202,NULL,'com/conviva/','Conviva','https://www.conviva.com/',NULL,'','ats','analytics',',dev,')
('auditude',203,NULL,'com/auditude/ads','Auditude','https://www.adobe.com/privacy/policies/auditude.html',NULL,'','ats','analytics',',dev,')
('instreamatic',204,NULL,'com/instreamatic','Instreamatic','http://instreamatic.com/',NULL,'','ats','analytics',',dev,')
```

Note that the `'ats','analytics',',dev,'` part is a place holder, meaning these tags are not necessarily correct; so the reason I haven't added those first entries most likely is I didn't know to categorize them – and the other ones have been added after 11/2018 (when I last updated the script) so I didn't check them yet…

Afraid not all of the tags can be matched to the categories (e.g. where would "billing" go to? Is "social" always "profiling"? What corresponds to "audio" or "android_utility"?) while others are easy (all "*_ads" are "Advertisement")…

**Comment by jawz101** [comment]
fwiw, a reference I found that had categories for about 7,040 different marketing companies is [this site](https://chiefmartec.com/2019/04/marketing-technology-landscape-supergraphic-2019/).  I filled out the form to dl their Excel file and used it along with Exodus, Izzy's lists, and a few other sources [here](https://github.com/jawz101/potentialTrackers/blob/master/potentialTrackers.csv) if it helps to fill in any blanks.

That csv is just a potential list I made to eventually get through to see if any of the companies had code signatures or SDK integration instructions to then put into ETIP... I have the list paired down to about 1,000 possible mobile ad/analytic companies.  Just don't know how many of the incomplete ones will result in a code signature yet.

**Comment by jawz101** [comment]
meh... Appbrain schmappbrain.  I want us to beat Appbrain's list :P

**Comment by simpnu** [comment]
I created a simple JSON file with the trackers from your dump which are on Exodus and had a category which fit our existing schema (which represents around 80 trackers). I'll try to import this data into ETIP soon.

[tracker_categories.txt](https://github.com/Exodus-Privacy/etip/files/3227441/tracker_categories.txt)

**Comment by simpnu** [comment]
I updated ETIP database with the information from the dump, the categories are now accessible on https://etip.exodus-privacy.eu.org
