### ISSUE TITLE
Suggestion to categorize tracker capabilities and behavior via labels / short summaries

### ISSUE THREAD

**Issue by seandiggity** [Exodus-Privacy/etip#32]
The tracker profiles can be very cumbersome to put together, and it's usually just more important to get the detection rules for the tracker into Exodus and not worry as much about the description.  However, maybe there's a happy medium here?  We could try to standardize labels we put on trackers, short summaries like the ones below.  Suggestions welcome, this is just an idea.

## Sensors &amp; Capabilities
* Tracks users using bluetooth
* Tracks users using ultrasonic
* Tracks users using location data
* Tracks users using GPS
* Tracks users using WiFi
* Tracks users using NFC
* Targets user location and proximity via geofencing
* Targets users via geotargeting

## Advertising
* Loads advertisements
* Loads targeted advertisements
* Real-world location targeting
* Targeted advertising based on consumer actions
* Timed advertisements
* Targets across devices, channels and/or platforms (omni-channel marketing, customer journey)
* Bidding services
* Location-based ad pushing
* Alters app functionality based upon user profiles

## Data Storage &amp; Analytics
* Offers analytics activity to app developers
* Offers reports to app developers
* Collects Personally Identifiable Information (PII)
* Collects Sensitive Personal Information (SPI)
* Profiles users via Personally Identifiable Information (PII)
* Profiles users via Sensitive Personal Information (SPI)
* Performs cross-device identification
* Identifies users via Google ID (AAID)
* Identifies users via iOS ID (IDFA)
* Identifies users via network ID (hostname/ISP/SSID)
* Stores facial recognition data
* Stores personal profile data (name, address, phone)
* Analytics AI and machine learning
* Audience segmenting

## Networks
* Data sharing
* Transmits user data to multiple ad networks
* Transmits information to Facebook ad network
* Transmits information to Google ad network
* Transmits information to Adobe ad network
* Transmits information to Yahoo! ad network
* Transmits information to Salesforce platform
* Transmits information to Twitter platform
* Transmits information to Amazon ad network
* Transmits information to Microsoft ad network

**Comment by simpnu** [comment]
To my knowledge these fields have been added to ETIP.
