### ISSUE TITLE
Highlight signature collisions

### ISSUE THREAD

**Issue by simpnu** [Exodus-Privacy/etip#37]
There is currently a feature to detect collisions in signatures (code or network) but we cannot see easily all the trackers with collisions (as we need to paginate through the trackers to find them).

This is how it looks currently:
![image](https://user-images.githubusercontent.com/6069449/58588479-068ebd80-8260-11e9-859b-473e3bff8a17.png)

We should highlight these collisions either by **allowing to filter only the trackers with collisions** or by **displaying them all at the top of the trackers table**.

**Comment by ammelanie** [comment]
I was trying to do this improvement but I face a performance issue. We need to iterate over each trackers for one tracker to see if there is a collision (this is the current behavior of `network_signature_collision` and `code_signature_collision`) and I don't think that we can paginate before.

For example, doing this 
```
if only_collision:
    trackers = list(t for t in trackers if t.network_signature_collision())
```

takes about 3 seconds on my local env. Adding `or t.code_signature_collision()` is doubling the time it takes. To solve this, we can have one method to check both collisions. But 3 seconds looks huge. What do you think, does it seem acceptable?

**Comment by simpnu** [comment]
Arg, I did not think about this (although now it seems obvious :)). I guess that removes the option to "display them all at the top of the trackers table".

If we add a button to only display the trackers with collisions and we write a new function to check for both collisions, that seems like a acceptable solution to me.

**Comment by ammelanie** [comment]
> I guess that removes the option to "display them all at the top of the trackers table"

Yup, I think. 

> If we add a button to only display the trackers with collisions and we write a new function to check for both collisions

Then, I'll continue with this and we will see if performance is acceptable :)
