### ISSUE TITLE
Script / page to check for recently updated signatures

### ISSUE THREAD

**Issue by simpnu** [Exodus-Privacy/etip#4]
I think it would be great to have a manual script or a webpage to load the trackers already in exodus which signature (code or network) were recently changed.

That would allow us to check ensure non regression with the trackers already in exodus.

**Comment by jawz101** [comment]
That would probably be a good idea.  At one point I went through the whole list looking for Maven repository info and other little things.  I'm sure I filled in the blanks on 20 or so trackers.

Bintray.com/adcompanyname
And
GitHub.com/adcompanyname

Seemed to find a bit out there 🙄

**Comment by simpnu** [comment]
I think #17 is a preferable solution to solve this issue, because this will allow us to immediately see any updates which were made to trackers in ETIP which are already integrated into Exodus.

I'm closing this issue, at least for the time being.
