### ISSUE TITLE
Please add tracker

### ISSUE THREAD

**Issue by ignis0902** [Exodus-Privacy/etip#51]
Please add a "tracker" admitad.com , I saw it in the client’s application for 4PDA, through the site VirusTotal -> Details -> Networks

**Comment by simpnu** [comment]
Hi @ignis0902

Sorry for the late reply!
I checked the app 4PDA and unfortunately couldn't find any code signature relative to admitad.com (it is possible/likely that the code is obfuscated and therefore we cannot see the embedded class).

**Comment by simpnu** [comment]
I added it nevertheless to ETIP but until we find matches in exodus we probably won't add it there.
