### ISSUE TITLE
adding maven repos as source of tracking lib binaries

### ISSUE THREAD

**Issue by eighthave** [Exodus-Privacy/etip#63]
I'm currently working with @reddr's [LibScout](https://github.com/reddr/LibScout) to automate the detection of tracking libraries in APKs.  This process needs the actual library binaries to build the profiles.  @reddr has some download sources for those binaries, I've been collecting more as I find them.  I think a natural place to gather that data would be in the Exodus ETIP database, but there would need to be new fields added, something like "Code Signature" and "Network Signature"

**Comment by eighthave** [comment]
@jawz101's https://github.com/jawz101/potentialTrackers also seems to have collected some of this info as well.

**Comment by simpnu** [comment]
Hi @eighthave!
There is already a field dedicated to this purpose in ETIP, called `maven_repository`, see https://etip.exodus-privacy.eu.org/trackers/110b2320-342c-41aa-a2c3-fab1a4dcdaad/ for instance

Note that currently this field is not imported in exodus so I don't know if the data is correctly set on every tracker in ETIP.

Do you think we need to make additional changes?

**Comment by eighthave** [comment]
That field looks correct, though the URL there is `https://mvnrepository.com/artifact/com.facebook.android/account-kit-sdk/`.  `mvnrepository.com` seems to be a meta repository, while I think the canonical repository there would be `https://repo1.maven.org/maven2/com/facebook/android/` (aka Maven Central).  As far as I know, jcenter also includes all of Maven Central, so this works also: https://jcenter.bintray.com/com/facebook/android/

The JSON at https://etip.exodus-privacy.eu.org/trackers/export does not include this field, it seems to have a lot fewer fields actually.  How should we consume this data?  Is there a better JSON URL?

**Comment by simpnu** [comment]
AFAIK the values can be changed (we don't use them currently in exodus, this is mostly to help on the research side). All you need to update the entries is an account on ETIP.

About the extract, note that we also have an API which allows to get this data (https://github.com/Exodus-Privacy/etip#api) although similarly to the extract function the `maven` entry won't be returned.

We can easily update one of these (or both) to extract the whole. Or even add a new API endpoint with the full entries.

What do you think is the most convenient for you and your team?
Feel free to directly propose a change if you have time and want to do so ;)

**Comment by eighthave** [comment]
I think it makes sense to get this info via the API.  It is currently not available in the API.  I don't know Django or web development well, and I didn't find the source of other fields in https://github.com/exodus-privacy/exodus .  These are the fields from ETIP that I think should be available via the API:

* `artifact_id`
* `gradle`
* `group_id`
* `maven_repository`

**Comment by eighthave** [comment]
So the current ETIP API does not include those four fields.  As far as I can tell, this change should add them to the API:

```diff
index 1d501c4..5ecae95 100644
--- a/etip/restful_api/serializers.py
+++ b/etip/restful_api/serializers.py
@@ -20,6 +20,10 @@ class TrackerSerializer(serializers.ModelSerializer):
           'is_in_exodus',
           'code_signature',
           'network_signature',
-          'website'
+          'website',
+          'maven_repository',
+          'group_id',
+          'artifact_id',
+          'gradle',
         ]
```
