### ISSUE TITLE
add inExodus flag and UUID to JSON dump

### ISSUE THREAD

**Issue by eighthave** [Exodus-Privacy/etip#64]
The web UI shows the "In Exodus" checkbox, then the links to the specific libraries include a UUID in the URL: `d5a1c328-2440-47fd-9241-bc04a7d0fffd` in https://etip.exodus-privacy.eu.org/admin/trackers/tracker/d5a1c328-2440-47fd-9241-bc04a7d0fffd/change/

These would be quite useful to have in the JSON dump.  I think I could code this if you would accept it.

**Comment by simpnu** [comment]
@eighthave Sure, feel free to add it to suit your needs!
If you need to get this data programmatically, you can take a look at the API instead (that we can modify as well)

**Comment by simpnu** [comment]
@eighthave Do you still need this?

**Comment by eighthave** [comment]
it would still be useful, e.g. to generate links to things in Exodus Privacy

**Comment by simpnu** [comment]
Ok, I'll take a look at this.

@eighthave Do you prefer to have this data in the export feature or the API?

**Comment by eighthave** [comment]
I think we can start with it in the API.

**Comment by simpnu** [comment]
The is_in_exodus flag is already present, I added the UUID in #69 and will release this soon
