### ISSUE TITLE
additional code detection rule for Crashlytics

### ISSUE THREAD

**Issue by IzzySoft** [Exodus-Privacy/etip#75]
Crashlytics (tracker id 27) needs an additional code detection rule I just discovered: `com.google.firebase.crashlytics` (for cross-checking, you can find that in e.g. `sk.henrichg.phoneprofiles` and `sk.henrichg.phoneprofilesplus`). So that should become `io.fabric. | com.crashlytics. | com.google.firebase.crashlytics.` Guess that comes with the move from Fabric to Firebase.

**Comment by simpnu** [comment]
Interesting!
I checked quickly and it adds detection of Crashlytics for 500+ new reports.

I'll add it to ETIP and then we'll move this to exodus when we'll add our next trackers!

Thanks @IzzySoft

**Comment by IzzySoft** [comment]
Gladly! Great to read – and thanks for checking!

**Comment by jfoucry** [comment]
Close this issue, new pattern has been added to ETIP

**Comment by IzzySoft** [comment]
Thanks for adding!
