### ISSUE TITLE
tracker help.  Unacast.com

### ISSUE THREAD

**Issue by jawz101** [Exodus-Privacy/etip#76]
I went down a rabbit hole on my list of potential trackers https://github.com/jawz101/potentialTrackers

and came across a company, [Unacast](https://www.unacast.com/), that is heavily involved in tracking mobility - so much so they're even grading zip codes for social distancing

https://www.unacast.com/covid19/social-distancing-scoreboard

https://in.mashable.com/tech/12523/this-company-youve-never-heard-of-says-it-knows-who-isnt-socially-distancing

https://www.vox.com/recode/2020/3/26/21192653/coronavirus-privacy-social-distancing-data-collection-unacast

I was wondering if we could get this one expedited.  I've began entering its details into ETIP if someone would take a look.
https://github.com/unacast/pure-sdk-android

**Comment by eighthave** [comment]
I downloaded their library, and looked at the publicly visible parts.  From that, it is clear to see.  So I added that to ETIP:

```
com.pure.internal.|com.pure.sdk.
```

**Comment by pnu-s** [comment]
Thanks @eighthave for the signature

After being reviewed by 2 people from Exodus Privacy, the tracker was added to exodus :tada: 
We will launch the recomputing of all our reports, but this takes a couple of hours

Thanks once more @jawz101 :+1:
