### ISSUE TITLE
application project: Perfect365

### ISSUE THREAD

**Issue by jawz101** [Exodus-Privacy/etip#79]
I was wondering if we could look at one app and find everything in it.

It looks like Perfect365 is clearly an app with the most trackers stuffed inside it and there is more to be found within it.  I've just been looking through the app's properties with another few apps that decompile or show receivers and services and there are some new names I'm seeing.

Considering they update this app so frequently, and how some of their app updates on Exodus find varying amounts of trackers, I'm sure they just stuff a new tracker in it every time they find one to use.

**Comment by pnu-s** [comment]
That's interesting, I just took a look at what's embedded with the latest version of the apps and I found a couple of trackers we don't have yet in exodus (or ETIP).
I'll try to take some time to create new profiles on ETIP.

@jawz101 What do you mean exactly by "look at one app and find everything in it"?

**Comment by jawz101** [comment]
Just pick it apart as you did, and just see if one app has more trackers than what signatures we already have.  I figure an app with 30 known trackers may have 5 additional trackers without signatures.
An app with 20+ trackers has made a point to monetize their app with as many 3rd parties as possible.

**Comment by pnu-s** [comment]
Cool!

FYI, I created profile for the following (new) trackers:
*  Mediabrix
* Tutela
* Footmarks

There is probably still more where it comes from :)

**Comment by jawz101** [comment]
Those were some of the ones I saw

**Comment by jawz101** [comment]
These are some of the notes I just made

https://www.kin.org/
com.kin.ecosystem
kin.sdk.exception

Stellar
https://www.stellar.org/	org.stellar.sdk.xdr.AccountID
https://developers.stellar.org/docs/software-and-sdks/
https://github.com/stellar/java-stellar-sdk

**unofficial, open source Twitter thing**
http://twitter4j.org
import twitter4j.conf.Configuration


**com.wirelessregistry.observersdk.observer.ObserverService**
I can't find much about this so far

**InMarket**
https://inmarket.com/
https://inmarket.com/sdk/
com.inmarket.m2m.internal.beaconservice.BeaconPeriodicTasksBroadcastReceiver

**Alibaba A Router**
https://github.com/alibaba/ARouter

**IAB**
com.iab.omid.library
https://iabtechlab.com/standards/open-measurement-sdk/
Some platform that seems to encapsulate other ad networks within it.

**Comment by jawz101** [comment]
I just added IAB and SignalFrame but the others I'm not sure would be considered trackers
