### ISSUE TITLE
Request to detect xmode tracker

### ISSUE THREAD

**Issue by hrj** [Exodus-Privacy/etip#83]
Please help detect this tracker: https://xmode.io/

I don't know which apps have this tracker, but as an app developer, I keep getting spammed by their marketing team for inclusion of their product in my app.

PS: Not sure if this is the right repo to make this request. Apologies in advance.

**Comment by pnu-s** [comment]
This is the right place to make this request ;)

Adding the tracker label.
For now I could not find any code signature in order to detect it.

**Comment by eighthave** [comment]
@rivkakarasik is this a tracker to be added?

**Comment by hrj** [comment]
One way to find their signature could be to use their opt-out / visualise apps described here:
https://xmode.io/location-data-privacy-matters-x-mode-releases-new-app-easyopt/

For example, the code in their opt-out app will try to access the advertising ID from some common file location or an `intent`. That location / `intent` could be used to get their signature.

**Comment by jfoucry** [comment]
Hum… found 229 times `xdk` (after looking to there website)
Nothing about `xmodesocial`
Not included to ETIP for know, issue stay open, the pattern is to large to be include without side effects.

**Comment by rivkakarasik** [comment]
I've added X-Mode as a tracker to the ETIP database (based on their privacy policy:https://xmode.io/xmode-privacy-policy-2/#section-2
in the news yesterday and today: https://www.wsj.com/articles/apple-and-google-to-stop-x-mode-from-collecting-location-data-from-users-phones-11607549061?mod=hp_lista_pos2

**Comment by pnu-s** [comment]
Closing this issue, the tracker profile is in ETIP and can be improved there: https://etip.exodus-privacy.eu.org/trackers/85776abf-95f1-4e4d-afde-be5f8493dac2/
