### ISSUE TITLE
Mozilla (Firefox) Contends False Positive

### ISSUE THREAD

**Issue by cyclingroo** [Exodus-Privacy/etip#84]
My name is Lorin Olsen (cyclingroo). And I am a user of this project. Like other privacy advocates, I trust Exodus (and ETIP) to determine the safety of Android applications (from either the Play Store or F-Droid). I have been working with Mozilla concerning the new Firefox for Android Beta. Earlier this year, Exodus started "detecting" Firefox for Android Beta (and other Firefox apps) as using Google AdMob and Google Firebase Analytics (as embedded trackers).  Per Mozilla (as found in [this Reddit thread](https://www.reddit.com/r/firefox/comments/ih1ibo/is_firefox_for_android_at_risk/)), Mozilla believes that they are not including either of these trackers.  I have told them to work with this project team - though I don't know if this has occurred.  Is there any way that we can verify the inclusion of these trackers and/or the assertions made by Mozilla?

**Comment by pnu-s** [comment]
Hello @cyclingroo and thanks for your message!

I took a look at that Reddit thread and the Mozilla employee states the following:

> What probably goes wrong with those analysers is that some specific Java class or a reference to a class is included in a build as an (indirect) dependency. **The presence of a class or reference to a class does not mean it is actively used**.

That's exactly what we say on the exodus platform, on each report:
>  This report lists trackers signatures found by static analysis in this APK. **This is not a proof of activity of these trackers**. 

Except by checking the published code of the application (and by being sure that this is the code which is running in the app), there is no way to know whether the trackers are active or not.
