### ISSUE TITLE
Add Jiguang JPush tracker

### ISSUE THREAD

**Issue by blaueente** [Exodus-Privacy/etip#89]
Please add the tracker SDK described here:

https://www.icsi.berkeley.edu/icsi/node/6407 
https://www.icsi.berkeley.edu/pubs/privacy/TR-20-001.pdf

> Our investigations into Android apps found that Chinese company Jiguang invasively monitors the activity of consumers who install apps that include their SDK. Jiguang’s SDK can collect consumers’ GPS locations, immutable device persistent identifiers, and even the names of all the apps they have installed—including when new ones are added or old ones removed. It does this collection even if the app that contains their code is not used. They send data over UDP sockets with misused cryptography, resulting in consumers’ personal data being trivially vulnerable to eavesdroppers. We observed their SDK communicating with Jiguang in 31 apps.

(note they also use hardcoded IPs, not only DNS hostnames)

**Comment by pnu-s** [comment]
I checked the code signature `cn.jiguang.sdk.jpush` and it doesn't catch anything in exodus database

If I look for `cn.jiguang.sdk` there are 20 reports with this signature

**Comment by blaueente** [comment]
What about `cn.jpush` and `cn.jiguang` ?

**Comment by pnu-s** [comment]
I found the signature `cn.jpush.android` according to their documentation:
https://github.com/jpush/jpush-android-samples

Matches 317 reports on exodus

I'll update this tracker profile: https://etip.exodus-privacy.eu.org/trackers/b2909a06-e5d8-470c-a755-a273ab20de04/

**Comment by blaueente** [comment]
Thanks for the tracker profile! I did a search before submitting, but could not find the entry, because I searched for "jiguang" and "jpush", not for "Aurora Mobile JPush". I added https://github.com/Exodus-Privacy/etip/issues/91 to make this easier in the future.

**Comment by blaueente** [comment]
Found that it might submit UDP messages on port 19000 to the following addresses:
```
s.jpush.cn
sis.jpush.io
easytomessage.com
123.196.118.23
103.229.215.60
117.121.49.100
```

also in some unknown way to:
```
im64.jpush.cn
_im64._tcp.jpush.cn
_psis._udp.jpush.cn
stats.jpush.cn
```

and http to:
```
http://182.92.20.189:9099/
https://tsis.jpush.cn
```

**Comment by pnu-s** [comment]
Tracker added today to exodus! :tada:

**Comment by blaueente** [comment]
> I checked the code signature `cn.jiguang.sdk.jpush` and it doesn't catch anything in exodus database
> 
> If I look for `cn.jiguang.sdk` there are 20 reports with this signature

@pnu-s : Is there a way for me to access this database in order to obtain similar statistics?

**Comment by pnu-s** [comment]
@blaueente Unfortunately this is not possible for the moment. This data is only on our production machines so can only be accessed by an Exodus Privacy member.

What I can offer is to check this data for you, starting with the trackers you created on ETIP.
We know it's not ideal, hopefully some day we can set an easier way to access those but it is not a trivial change.
