### ISSUE TITLE
TagCommander accidental dupe signature

### ISSUE THREAD

**Issue by jawz101** [Exodus-Privacy/etip#90]
I just made a signature for TagCommander.  It turns out there was already an entry for it.  I went ahead and updated the existing entry with more info (description, documentation, maven repository, additional url, more specific company name) but I cannot delete my old entry

https://etip.exodus-privacy.eu.org/?tracker_name=tagc

**Comment by jawz101** [comment]
oops.  nevermind.  found the delete button.  Anyways, there should be more info in there now if anyone is interested.

**Comment by pnu-s** [comment]
Changes integrated into exodus, thanks!
