### ISSUE TITLE
Detect taobao / umeng push sdk

### ISSUE THREAD

**Issue by blaueente** [Exodus-Privacy/etip#92]
https://www.linkedin.com/company/umeng

> Umeng, a Beijing-based startup, is the leading provider of mobile app analytics in China.  Incubated by Innovation Works, Umeng was originally founded in April 2010 and was acquired by Alibaba in 2013. 
> 
> Umeng's state-of-the-art mobile app analytics and data-powered cross-promotion/advertising platform helps mobile apps increase the size and value of audiences.  Umeng offers enterprise-class analytics and other solutions to hundred thousands of mobile app companies in over 65,000 apps across iOS, Android, and other platforms.

Some classes that might belong to the Push sdk:

com.taobao.accs.ChannelService
com.taobao.accs.data.MsgDistributeService
com.taobao.accs.internal.AccsJobService
com.taobao.accs.ChannelService$KernelService
com.taobao.accs.EventReceiver
com.taobao.accs.ServiceReceiver
com.taobao.agoo.AgooCommondReceiver
org.android.agoo.accs.AgooService
com.umeng.message.UmengIntentService
com.umeng.message.XiaomiIntentService
com.umeng.message.UmengMessageIntentReceiverService
com.umeng.message.UmengMessageCallbackHandlerService
com.umeng.message.UmengDownloadResourceService

Quite invasive, as it receives "USER_PRESENT" intents.

see also https://github.com/umeng/UMAndroidSdkDemo/blob/16d2f43fe3a9ff462895861dbd72a0f1cda296f6/PushSDK/AndroidManifest.xml 
https://developer.umeng.com/docs/67966/detail/153908
https://github.com/umeng/UMAndroidSdkDemo

**Mobile tracking SDK**
seems something different to the push SDK:
https://developer.umeng.com/docs/119267/detail/118584
com.umeng.umsdk

Given the self-advertisement above, I don't think this company makes any non-tracking code, so it would probably be a good idea to just insert a catchall:
`com.umeng`

**Comment by blaueente** [comment]
Found the following IPs, domains, and urls:
```
100.69.165.28
110.75.98.154
100.69.168.33
agoodm.m.taobao.com
```

```
http://agoodm.m.taobao.com/agoo/report
http://agoodm.wapa.taobao.com/agoo/report
http://100.69.165.28/agoo/report
http://100.69.168.33/agoo/report
```

**Comment by blaueente** [comment]
class
`anet.channel`

found this in an app. not sure what it does.

contains the following domains as strings.

```
amdc.m.taobao.com
amdc.wapa.taobao.com
amdc.taobao.net
dorangesource.alicdn.com
guide-acs.m.taobao.com
gw.alicdn.com
ossgw.alicdn.com
```

also contains other strings such as:
```
appkey
appName
appVersion
bssid
carrier
channel
deviceId
com.taobao.analysis.FlowCenter
DefaultNetworkAnalysis
no NWNetworkAnalysisSDK sdk
awcn.TaobaoNetworkAdapter
taobao speed mode enable.
Network detail*******************************
app background, forbid to create accs session
accs session connecting forbidden in background
app background, forbid to create accs session
getProcessNameNew
ps  |  grep  
```

So it seems pretty clear to me that it deals with networks, network identifiers, is somehow related to that accs, and the "ps | grep" smells of data collection.
In best case it is some connection library, but then even this should be recorded.
Did some research with google, but could not find anything helpful.

**Comment by jfoucry** [comment]
Hello @blaueente,

It seems you are a great tacker hunter. 

May be It could be interesting for you and us to use our ETIP platform which is dedecaded to  add trackers in a database before we add them into εxodus. If you're want an account on ETIP, just ask by mail at contact@exodus-privacy.eu.org.

Thanks for all the trackers you already found.

**Comment by blaueente** [comment]
That would be great, I'll do that! I am not sure when I will go tracker hunting next time, though. Probably when I need to use another shady app ;)

**Comment by blaueente** [comment]
Added to ETIP
